import Head from 'next/head'
import CryptoList from '../components/cryptoList'
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { resetServerContext } from 'react-beautiful-dnd';
import { DragDropContext } from 'react-beautiful-dnd';
import {useEffect, useState} from "react"




export default function Home({ data }) {

  const correctOrder=([
    {
        name:"btc",
        id:"btc"
    },
    {
        name:"eth",
        id:"eth"
    },
    {
      name:"bnb",
      id:"bnb"
    },
    {
      name:"matic",
      id:"matic"
    },
    {
        name:"ltc",
        id:"ltc"
    }
    
    
  ])

  const [orderedList, setOrderedList]= useState([
    {
        name:"btc",
        id:"btc"
    },
    {
        name:"eth",
        id:"eth"
    },
    {
        name:"ltc",
        id:"ltc"
    },
    {
        name:"bnb",
        id:"bnb"
    },
    {
        name:"matic",
        id:"matic"
    }
  ])
  

  const handleOnDragEnd = (result)=>{
    const coins = Array.from(orderedList);
    const [reorderList] = coins.splice(result.source.index, 1)
    coins.splice(result.destination.index, 0, reorderList)
    setOrderedList(coins)
  }


  return (
    <div >
      <Head>
        <title>Can You Order The List?</title>
        <meta name="description" content="Generated by dez nuts" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="xs" sx={{textAlign:"center", height:"100vh", display:"flex", flexDirection:"column",justifyContent:"center"}}>
        
        <Typography variant="h2"  color="secondary">
          Order The List
        </Typography>

        
        <DragDropContext onDragEnd={handleOnDragEnd}>
          <CryptoList orderedList={orderedList} setOrderedList={setOrderedList}/>
        </DragDropContext>
          
        
        
        

        <Button variant="contained" color="secondary">Check Order</Button>

      </Container>

      
    </div>
  )
}

export const getServerSideProps = async ({ query }) => {

  resetServerContext()   
  
  return {props: { data : []}}


}
